server:
  port: 9998
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.jinelei.numbfish.device.client.controller

# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
  # 开启Swagger的Basic认证功能,默认是false
  basic:
    enable: true
    # Basic认证用户名
    username: numbfish
    # Basic认证密码
    password: numbfish

# Logger Config
logging:
  level:
    root: warn
    com.jinelei: debug

spring:
  application:
    name: numbfish-device-service
  banner:
    location: banner.txt
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/iotgenius?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: iotG@2025
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: iotG@2025
      database: 0
      lettuce:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0

mybatis:
  mapper-locations: classpath*:mapper/*/*Mapper.xml,classpath*:mapper/*Mapper.xml
  type-handlers-package: com.jinelei.numbfish.device.client.configuration.handler.type
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
numbfish:
  authorization:
    admin:
      username: admin
    login:
      url: /user/login
    ignore:
      urls:
        - /webjars
        - /doc.html
